version: "3.9"
services:
  cdk:
    # user: "node:node"
    environment:
      - HOME=/home/node
    build: ./
    working_dir: /home/node/workspace
    tty: true
    volumes:
      - "../:/home/node/workspace:cached"
      - "~/.ssh:/home/node/.ssh:cached"
      - "~/.aws:/home/node/.aws:cached"
    command: /bin/sh -c "while sleep 1000; do :; done"
